import type { Metadata } from "next";
import { ABeeZee } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const comforter = ABeeZee({ 
  subsets: ["latin"],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comforter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}